# Generated by Django 4.0.5 on 2022-11-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default='i59ednt', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('class_standard', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base.class')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='base.teacher')),
            ],
        ),
    ]
