# Generated by Django 4.0.5 on 2022-11-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_student_name_remove_teacher_name_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='username',
            new_name='user',
        ),
    ]
