# Generated by Django 4.0.5 on 2022-11-20 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_class_student_class_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='standard',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
            ],
        ),
    ]
