# Generated by Django 4.0.5 on 2022-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_class_standard_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['standard']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_standard',
        ),
        migrations.AddField(
            model_name='subject',
            name='class_standard',
            field=models.ManyToManyField(to='base.class'),
        ),
    ]
